# Generated by Django 5.0.1 on 2024-01-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='projector_available',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
