# Generated by Django 5.0.1 on 2024-01-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_room_projector_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='projector_available',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
