# Generated by Django 5.0.1 on 2024-01-13 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_room_id_reservation_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meta',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.room', unique_for_date='date'),
        ),
    ]
